language: php
php:
  - 7.1.9
before_script:
  - composer install
script:
  - phpunit --no-coverage indexTest.php
deploy:
  api_key:
    secure: Ue8A/CUFccItVh6JSLdN3MJaVPWxQRu+SDsLhISi98u2zxKsPAt+v0RZ2w/X3+wl+6clY/t4OGjLhvggYoOtV5D2yDCAMtp0GWY+NvkaOkmjtMzqJAqdIZL9tOruPJcopskIutxe/qKwlQ5F8F5m7qRHcbVjwXazfqU5Cds4904pCqS3WsW95btyXGNhadVXmDQQdydthCh/ZU/6/ifCzKhQdPzPJ76UXwJNYyxQjAiTw/0scLGnsRYPdeveBzhoukK+QK8cVfMYa3JNWd8xJDhOAaxxV006q2WVz3Yf6z2FVks/gjp46i0cxf1HCv1eXicGGUNVgWEy112P/NwMzgoITYObBxPctIgFwJb683y26P1dYpp6ErVOikERL0pWAlrcbXNW7hLt/uMAbThcfQrZ79v4koKqsQguQYOQVnPPCjhDqf4OyUrF5mDVK1FdyqhQtmJka8mFHnki8b4sg2UjzIWDGvl+giqaCevWvT5pY6bLsbK/ME8jvk6Miy1EcuT/qeFcgywvrmBC+aw2KxFAEFlqjg0U38AemSK3EhKSExvfAl6MHs257Q7dE0nJSWl0VnZl1HG0xHHMP7QnGlL8oI0yXEXwLKkl2q8nEHSi2qiK2O4DbqoKV4Z2fe6gTyVC7KUsapJcCbL/LvYGbGbtNK7ZmRYLJPbZVyleyXo=  
  app:
    master: devops-stt10
